version: '3.8'

services:
  database:
    image: postgres:15
    container_name: forwarder_backend_database
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: forwarder_backend_application
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
volumes:
  postgres_data: