# Профиль для запуска на локале у разработчика
server:
  address: 127.0.0.1

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/telegram_forwarder"
    username: test
    password: test

telegram-bot-starter:
  bot:
    token: YOUR_TEST_BOT_TOKEN

management:
  endpoints:
    web:
      exposure:
        include: beans