# Профиль для запуска на локале у разработчика
server:
  address: 127.0.0.1

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/telegram_forwarder"
    username: test
    password: test

message-fetcher:
  url: message-fetcher/

telegram-bot-starter:
  bot:
    token: 7990515025:AAHo9MyYefC6mVmoykCSs40asp-vp8Bdk9c