# Профиль для запуска на локале у разработчика
server:
  address: 127.0.0.1

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/telegram_forwarder"
    username: test
    password: test
  security:
    user:
      name: admin
      password: admin

api:
  get-message-url: http://127.0.0.1:4322/get-subscription-messages
  join-group-url: http://127.0.0.1:4322/join-group
  lemmatization-url: http://127.0.0.1:4355/lemmatize
  ocr-url: http://127.0.0.1:4366/image-to-text
telegram-bot-starter:
  bot:
    token: test_bot_token