# Профиль для запуска на локале у разработчика
server:
  address: 127.0.0.1

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/telegram_forwarder"
    username: test
    password: test

telegram-forwarder-user: devuser
telegram-bot-starter:
  bot:
    token: dev-token-bot