# Профиль для запуска на локале у разработчика
server:
  address: 127.0.0.1

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/telegram_forwarder"
    username: test
    password: test

telegram-forwarder-user: resenderuser
telegram-bot-starter:
  bot:
    token: 7596219963:AAFTEgB5XXQ8E_xsLLWL_1JYghH-xqwHhgE

management:
  endpoints:
    web:
      exposure:
        include: beans