server:
  port: 8080

spring:
  profiles:
    active: prod
  liquibase:
    change-log: classpath:/db/changelog.yaml
  datasource:
    url: "jdbc:postgresql://${POSTGRES_PATH}:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: forwarder_backend
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

message-fetcher:
  url: http://sender:4322/get-subscription-messages

telegram-bot-starter:
  bot:
    token: ${FORWARDER_BACKEND_BOT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    diskspace:
      enabled: true
      path: /
      threshold: 1000MB
    db:
      enabled: true

logging:
  level:
    root: INFO