# Профиль для запуска на локале у разработчика
server:
  address: 127.0.0.1

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/telegram_forwarder"
    username: test
    password: test
  security:
    user:
      name: admin
      password: admin

message-fetcher:
  url: http://127.0.0.1:4322/get-subscription-messages

telegram-bot-starter:
  bot:
    token: your_bot_token