server:
  port: 8080

spring:
  profiles:
    active: prod
  liquibase:
    change-log: classpath:/db/changelog.yaml
  datasource:
    url: "jdbc:postgresql://${POSTGRES_PATH}:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: forwarder_backend
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    user:
      name: ${BACKEND_BASIC_AUTH_USER}
      password: ${BACKEND_BASIC_AUTH_PASSWORD}

api:
  get-message-url: http://sender:4322/get-subscription-messages
  lemmatization-url: http://lemmatizer:4355/lemmatize
  ocr-url: http://ocr:4366/image-to-text
rest-template:
  connection-timeout: 20000

telegram-bot-starter:
  bot:
    token: ${FORWARDER_BACKEND_BOT_SECRET_KEY}

scheduler:
  pool-size: 3
  antispam-delay: 500

cache:
  max-size: 100000

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    diskspace:
      enabled: true
      path: /
      threshold: 1000MB
    db:
      enabled: true

logging:
  level:
    root: INFO