/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.public_.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import ru.lashnev.forwarderbackend.dao.jooq.public_.Keys;
import ru.lashnev.forwarderbackend.dao.jooq.public_.Public;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.Subscriptions.SubscriptionsPath;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.records.GroupsRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Groups extends TableImpl<GroupsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.groups</code>
     */
    public static final Groups GROUPS = new Groups();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupsRecord> getRecordType() {
        return GroupsRecord.class;
    }

    /**
     * The column <code>public.groups.group_id</code>.
     */
    public final TableField<GroupsRecord, Integer> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.groups.groupname</code>.
     */
    public final TableField<GroupsRecord, String> GROUPNAME = createField(DSL.name("groupname"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.groups.invalid</code>.
     */
    public final TableField<GroupsRecord, Boolean> INVALID = createField(DSL.name("invalid"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.groups.lastmessageid</code>.
     */
    public final TableField<GroupsRecord, Long> LASTMESSAGEID = createField(DSL.name("lastmessageid"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private Groups(Name alias, Table<GroupsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Groups(Name alias, Table<GroupsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.groups</code> table reference
     */
    public Groups(String alias) {
        this(DSL.name(alias), GROUPS);
    }

    /**
     * Create an aliased <code>public.groups</code> table reference
     */
    public Groups(Name alias) {
        this(alias, GROUPS);
    }

    /**
     * Create a <code>public.groups</code> table reference
     */
    public Groups() {
        this(DSL.name("groups"), null);
    }

    public <O extends Record> Groups(Table<O> path, ForeignKey<O, GroupsRecord> childPath, InverseForeignKey<O, GroupsRecord> parentPath) {
        super(path, childPath, parentPath, GROUPS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GroupsPath extends Groups implements Path<GroupsRecord> {
        public <O extends Record> GroupsPath(Table<O> path, ForeignKey<O, GroupsRecord> childPath, InverseForeignKey<O, GroupsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GroupsPath(Name alias, Table<GroupsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GroupsPath as(String alias) {
            return new GroupsPath(DSL.name(alias), this);
        }

        @Override
        public GroupsPath as(Name alias) {
            return new GroupsPath(alias, this);
        }

        @Override
        public GroupsPath as(Table<?> alias) {
            return new GroupsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GroupsRecord, Integer> getIdentity() {
        return (Identity<GroupsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GroupsRecord> getPrimaryKey() {
        return Keys.GROUPS_PKEY;
    }

    @Override
    public List<UniqueKey<GroupsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.GROUPS_GROUPNAME_KEY);
    }

    private transient SubscriptionsPath _subscriptions;

    /**
     * Get the implicit to-many join path to the
     * <code>public.subscriptions</code> table
     */
    public SubscriptionsPath subscriptions() {
        if (_subscriptions == null)
            _subscriptions = new SubscriptionsPath(this, null, Keys.SUBSCRIPTIONS__KEYWORDS_GROUP_ID_FKEY.getInverseKey());

        return _subscriptions;
    }

    @Override
    public Groups as(String alias) {
        return new Groups(DSL.name(alias), this);
    }

    @Override
    public Groups as(Name alias) {
        return new Groups(alias, this);
    }

    @Override
    public Groups as(Table<?> alias) {
        return new Groups(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Groups rename(String name) {
        return new Groups(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Groups rename(Name name) {
        return new Groups(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Groups rename(Table<?> name) {
        return new Groups(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups where(Condition condition) {
        return new Groups(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Groups where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Groups where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Groups where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Groups where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Groups whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
