/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.public_.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import ru.lashnev.forwarderbackend.dao.jooq.public_.Keys;
import ru.lashnev.forwarderbackend.dao.jooq.public_.Public;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.records.SubscriptionsOldRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubscriptionsOld extends TableImpl<SubscriptionsOldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.subscriptions_old</code>
     */
    public static final SubscriptionsOld SUBSCRIPTIONS_OLD = new SubscriptionsOld();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubscriptionsOldRecord> getRecordType() {
        return SubscriptionsOldRecord.class;
    }

    /**
     * The column <code>public.subscriptions_old.subscription_id</code>.
     */
    public final TableField<SubscriptionsOldRecord, Integer> SUBSCRIPTION_ID = createField(DSL.name("subscription_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.subscriptions_old.subscriber</code>.
     */
    public final TableField<SubscriptionsOldRecord, String> SUBSCRIBER = createField(DSL.name("subscriber"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.subscriptions_old.subscription</code>.
     */
    public final TableField<SubscriptionsOldRecord, String> SUBSCRIPTION = createField(DSL.name("subscription"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.subscriptions_old.keyword</code>.
     */
    public final TableField<SubscriptionsOldRecord, String> KEYWORD = createField(DSL.name("keyword"), SQLDataType.VARCHAR.nullable(false), this, "");

    private SubscriptionsOld(Name alias, Table<SubscriptionsOldRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SubscriptionsOld(Name alias, Table<SubscriptionsOldRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.subscriptions_old</code> table reference
     */
    public SubscriptionsOld(String alias) {
        this(DSL.name(alias), SUBSCRIPTIONS_OLD);
    }

    /**
     * Create an aliased <code>public.subscriptions_old</code> table reference
     */
    public SubscriptionsOld(Name alias) {
        this(alias, SUBSCRIPTIONS_OLD);
    }

    /**
     * Create a <code>public.subscriptions_old</code> table reference
     */
    public SubscriptionsOld() {
        this(DSL.name("subscriptions_old"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SubscriptionsOldRecord, Integer> getIdentity() {
        return (Identity<SubscriptionsOldRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SubscriptionsOldRecord> getPrimaryKey() {
        return Keys.SUBSCRIPTIONS_PKEY;
    }

    @Override
    public List<UniqueKey<SubscriptionsOldRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SUBSCRIPTIONS_SUBSCRIBER_SUBSCRIPTION_KEYWORD_KEY);
    }

    @Override
    public SubscriptionsOld as(String alias) {
        return new SubscriptionsOld(DSL.name(alias), this);
    }

    @Override
    public SubscriptionsOld as(Name alias) {
        return new SubscriptionsOld(alias, this);
    }

    @Override
    public SubscriptionsOld as(Table<?> alias) {
        return new SubscriptionsOld(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SubscriptionsOld rename(String name) {
        return new SubscriptionsOld(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SubscriptionsOld rename(Name name) {
        return new SubscriptionsOld(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SubscriptionsOld rename(Table<?> name) {
        return new SubscriptionsOld(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubscriptionsOld where(Condition condition) {
        return new SubscriptionsOld(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubscriptionsOld where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubscriptionsOld where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubscriptionsOld where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SubscriptionsOld where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SubscriptionsOld where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SubscriptionsOld where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SubscriptionsOld where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubscriptionsOld whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubscriptionsOld whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
