/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.public_.tables.records;


import org.jooq.Record1;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.Keywords;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KeywordsRecord extends UpdatableRecordImpl<KeywordsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.keywords.keyword_id</code>.
     */
    public void setKeywordId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.keywords.keyword_id</code>.
     */
    public Integer getKeywordId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.keywords.keyword</code>.
     */
    public void setKeyword(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.keywords.keyword</code>.
     */
    public String getKeyword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.keywords.subscriber_id</code>.
     */
    public void setSubscriberId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.keywords.subscriber_id</code>.
     */
    public Integer getSubscriberId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.keywords.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.keywords.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KeywordsRecord
     */
    public KeywordsRecord() {
        super(Keywords.KEYWORDS);
    }

    /**
     * Create a detached, initialised KeywordsRecord
     */
    public KeywordsRecord(Integer keywordId, String keyword, Integer subscriberId, Integer groupId) {
        super(Keywords.KEYWORDS);

        setKeywordId(keywordId);
        setKeyword(keyword);
        setSubscriberId(subscriberId);
        setGroupId(groupId);
        resetChangedOnNotNull();
    }
}
