/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.public_.tables.records;


import org.jooq.Record1;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.Searches;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SearchesRecord extends UpdatableRecordImpl<SearchesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.searches.search_id</code>.
     */
    public void setSearchId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.searches.search_id</code>.
     */
    public Integer getSearchId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.searches.properties</code>.
     */
    public void setProperties(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.searches.properties</code>.
     */
    public String getProperties() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SearchesRecord
     */
    public SearchesRecord() {
        super(Searches.SEARCHES);
    }

    /**
     * Create a detached, initialised SearchesRecord
     */
    public SearchesRecord(Integer searchId, String properties) {
        super(Searches.SEARCHES);

        setSearchId(searchId);
        setProperties(properties);
        resetChangedOnNotNull();
    }
}
