/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.public_.tables.records;


import org.jooq.Record1;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.SubscriptionsOld;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubscriptionsOldRecord extends UpdatableRecordImpl<SubscriptionsOldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.subscriptions_old.subscription_id</code>.
     */
    public void setSubscriptionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.subscriptions_old.subscription_id</code>.
     */
    public Integer getSubscriptionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.subscriptions_old.subscriber</code>.
     */
    public void setSubscriber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.subscriptions_old.subscriber</code>.
     */
    public String getSubscriber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.subscriptions_old.subscription</code>.
     */
    public void setSubscription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.subscriptions_old.subscription</code>.
     */
    public String getSubscription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.subscriptions_old.keyword</code>.
     */
    public void setKeyword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.subscriptions_old.keyword</code>.
     */
    public String getKeyword() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubscriptionsOldRecord
     */
    public SubscriptionsOldRecord() {
        super(SubscriptionsOld.SUBSCRIPTIONS_OLD);
    }

    /**
     * Create a detached, initialised SubscriptionsOldRecord
     */
    public SubscriptionsOldRecord(Integer subscriptionId, String subscriber, String subscription, String keyword) {
        super(SubscriptionsOld.SUBSCRIPTIONS_OLD);

        setSubscriptionId(subscriptionId);
        setSubscriber(subscriber);
        setSubscription(subscription);
        setKeyword(keyword);
        resetChangedOnNotNull();
    }
}
