/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.public_.tables.records;


import org.jooq.Record1;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.Subscriptions;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubscriptionsRecord extends UpdatableRecordImpl<SubscriptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.subscriptions.subscription_id</code>.
     */
    public void setSubscriptionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.subscriptions.subscription_id</code>.
     */
    public Integer getSubscriptionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.subscriptions.subscriber_id</code>.
     */
    public void setSubscriberId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.subscriptions.subscriber_id</code>.
     */
    public Integer getSubscriberId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.subscriptions.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.subscriptions.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.subscriptions.search_id</code>.
     */
    public void setSearchId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.subscriptions.search_id</code>.
     */
    public Integer getSearchId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubscriptionsRecord
     */
    public SubscriptionsRecord() {
        super(Subscriptions.SUBSCRIPTIONS);
    }

    /**
     * Create a detached, initialised SubscriptionsRecord
     */
    public SubscriptionsRecord(Integer subscriptionId, Integer subscriberId, Integer groupId, Integer searchId) {
        super(Subscriptions.SUBSCRIPTIONS);

        setSubscriptionId(subscriptionId);
        setSubscriberId(subscriberId);
        setGroupId(groupId);
        setSearchId(searchId);
        resetChangedOnNotNull();
    }
}
