/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.tables.records;


import org.jooq.Record1;
import ru.lashnev.forwarderbackend.dao.jooq.tables.Groups;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupsRecord extends UpdatableRecordImpl<GroupsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.groups.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.groups.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.groups.groupname</code>.
     */
    public void setGroupname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.groups.groupname</code>.
     */
    public String getGroupname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.groups.invalid</code>.
     */
    public void setInvalid(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.groups.invalid</code>.
     */
    public Boolean getInvalid() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.groups.lastmessageid</code>.
     */
    public void setLastmessageid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.groups.lastmessageid</code>.
     */
    public Long getLastmessageid() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupsRecord
     */
    public GroupsRecord() {
        super(Groups.GROUPS);
    }

    /**
     * Create a detached, initialised GroupsRecord
     */
    public GroupsRecord(Integer groupId, String groupname, Boolean invalid, Long lastmessageid) {
        super(Groups.GROUPS);

        setGroupId(groupId);
        setGroupname(groupname);
        setInvalid(invalid);
        setLastmessageid(lastmessageid);
        resetChangedOnNotNull();
    }
}
