/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.tables.records;


import org.jooq.Record1;
import ru.lashnev.forwarderbackend.dao.jooq.tables.Subscribers;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubscribersRecord extends UpdatableRecordImpl<SubscribersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.subscribers.subscriber_id</code>.
     */
    public void setSubscriberId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.subscribers.subscriber_id</code>.
     */
    public Integer getSubscriberId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.subscribers.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.subscribers.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.subscribers.chatid</code>.
     */
    public void setChatid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.subscribers.chatid</code>.
     */
    public String getChatid() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubscribersRecord
     */
    public SubscribersRecord() {
        super(Subscribers.SUBSCRIBERS);
    }

    /**
     * Create a detached, initialised SubscribersRecord
     */
    public SubscribersRecord(Integer subscriberId, String username, String chatid) {
        super(Subscribers.SUBSCRIBERS);

        setSubscriberId(subscriberId);
        setUsername(username);
        setChatid(chatid);
        resetChangedOnNotNull();
    }
}
