/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.public_;


import org.jooq.Index;
import org.jooq.OrderField;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.Subscriptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index UNIQUE_SUBSCRIBER_GROUP_SEARCH = Internal.createIndex(DSL.name("unique_subscriber_group_search"), Subscriptions.SUBSCRIPTIONS, new OrderField[] { Subscriptions.SUBSCRIPTIONS.SUBSCRIBER_ID, Subscriptions.SUBSCRIPTIONS.GROUP_ID, Subscriptions.SUBSCRIPTIONS.SEARCH_ID }, true);
}
