/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq.public_;

import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.Groups;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.Searches;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.Subscribers;
import ru.lashnev.forwarderbackend.dao.jooq.public_.tables.Subscriptions;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.groups</code>.
     */
    public static final Groups GROUPS = Groups.GROUPS;

    /**
     * The table <code>public.searches</code>.
     */
    public static final Searches SEARCHES = Searches.SEARCHES;

    /**
     * The table <code>public.subscribers</code>.
     */
    public static final Subscribers SUBSCRIBERS = Subscribers.SUBSCRIBERS;

    /**
     * The table <code>public.subscriptions</code>.
     */
    public static final Subscriptions SUBSCRIPTIONS = Subscriptions.SUBSCRIPTIONS;
}
