/*
 * This file is generated by jOOQ.
 */
package ru.lashnev.forwarderbackend.dao.jooq;


import ru.lashnev.forwarderbackend.dao.jooq.tables.Databasechangelog;
import ru.lashnev.forwarderbackend.dao.jooq.tables.Databasechangeloglock;
import ru.lashnev.forwarderbackend.dao.jooq.tables.Groups;
import ru.lashnev.forwarderbackend.dao.jooq.tables.Keywords;
import ru.lashnev.forwarderbackend.dao.jooq.tables.Subscribers;
import ru.lashnev.forwarderbackend.dao.jooq.tables.SubscriptionsOld;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.groups</code>.
     */
    public static final Groups GROUPS = Groups.GROUPS;

    /**
     * The table <code>public.keywords</code>.
     */
    public static final Keywords KEYWORDS = Keywords.KEYWORDS;

    /**
     * The table <code>public.subscribers</code>.
     */
    public static final Subscribers SUBSCRIBERS = Subscribers.SUBSCRIBERS;

    /**
     * The table <code>public.subscriptions_old</code>.
     */
    public static final SubscriptionsOld SUBSCRIPTIONS_OLD = SubscriptionsOld.SUBSCRIPTIONS_OLD;
}
